import Head from 'next/head'
// import Image from 'next/image' {styles.container}
import Header from '../components/Header';
import Feed from '../components/Feed';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Pawsta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {/* feed */}
      <Feed />

      {/* modal */}

    </div>
  );
}
